#define MASTER_RIGHT

#define COMBO_TERM 50

#define TAPPING_TERM 200
#define QUICK_TAP_TERM 0
#define PERMISSIVE_HOLD

//#define TAPPING_FORCE_HOLD
#define HOLD_ON_OTHER_KEY_PRESS

#define TAPPING_TOGGLE 2